### ISSUE TITLE
fix release archive format

### ISSUE THREAD

**Issue by 0pcom** [skycoin/skybian#27] opened 2020-04-20 15:07 UTC
**Describe the bug**
I can't extract the skyimager release from the command line. It's supposed to auto-extract with makepkg when an archive such as this is specified in the source array.

I can extract it in thunar with, I guess, archivemanager or file-roller but `tar -xf` doesn't work

**Environment information:**

- OS: Archlinux
- Platform: Linux 5.6.3-arch1-1 x86_64

**Steps to Reproduce**

1. download skyimager
2. `tar -xf skyimager-linux-amd64-v0.1.2.tar.xz`
3.
```
tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors
```

**Actual behavior**
listed above

**Expected behavior**
file extracts from the command line

**Additional context**
I had to reupload this to skyfleet with the right archive format so it extracts as expected.

**Possible implementation**
```
tar -czvf  skyimager-linux-amd64-v0.1.2.tar.xz /path/to/skyimager
```

**Comment by nkryuchkov** [comment] 2020-10-08 11:09
The problem is that an archive is created using `tar/gzip` format and then archived again with `xz`: https://github.com/skycoin/skybian/blob/master/build-skyimager.sh#L28.

This will be fixed by https://github.com/skycoin/skybian/pull/45.

Next archives will be created with just `tar/gzip` and will have the `.tar.gz` extension.

For existing archives, please use the following:
```
xz -d skyimager-linux-amd64-v0.1.2.tar.xz
tar -xf skyimager-linux-amd64-v0.1.2.tar
```

**Closed as completed** 2020-10-21 08:40 UTC
Labels: bug
